services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "links"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
        - "5432:5432"
    volumes:
        - postgres:/var/lib/postgresql/data
  core:
    restart: always
    depends_on:
        - "postgres"
    container_name: test
    build:
        dockerfile: Dockerfile
        context: .
    environment:
      POSTGRES: "postgres://postgres:1234@postgres:5432?sslmode=disable"
      HOST: 0.0.0.0:8090
      DOMEN: "http://localhost/" 
      #"http://team5.itatmisis.ru/"
    ports:
      - '80:8090'
volumes:
  postgres: