ervices:
  postgres:
    image: postgres:16.6
    environment:
      POSTGRES_DB: "links"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
        - "127.0.0.1:5432:5432" 
    volumes:
        - postgres:/var/lib/postgresql/data

  core:
    restart: always
    depends_on:
        - "postgres"
    container_name: test
    build:
        dockerfile: ./deploy/DockerfileGo
        context: .
    env_file:
      - dev.env
    ports:
      - '80:8090'
    
  bot:
    image: python:3.10
    depends_on:
      - "core"
      - "postgres"
    build:
        dockerfile: ./deploy/DockerfilePython
        context: .
        network: host
    env_file:
      - dev.env
    command: ["python3", "main.py"]

volumes:
  postgres:
